spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

jwt:
  expiration: 1d

password:
  encryption:
    key: encryptedtesting


server:
  port: 9090